### ISSUE TITLE
Duplicates in Bach

### ISSUE THREAD

**Issue by stefan-balke** [CPJKU/msmd#2]
Hi,

`BachJS__BWV827__BWV-827`
 
and

`BachJS__BWV830__BWV-830`

have duplicates with, e.g., `BachJS__BWV830__BWV-830-1`.

Or am I missing something?

**Comment by dmatte** [comment]
Hi Stefan,

I think this should be fine. If you take for example a look at the split file
```
msmd/msmd/splits/all_split.yaml
```
you will only find the individual movements:
- BachJS__BWV827__BWV-827-1
- BachJS__BWV827__BWV-827-2
- ...

So for the pieces where duplicate LilyPond files where available
we only consider the individual movements.
