### ISSUE TITLE
Some pieces have empty performances

### ISSUE THREAD

**Issue by mjenrungrot** [CPJKU/msmd#3]
In the preprocessed dataset, some pieces (for example `BachJS__BWV800__bwv800`) do not have any performance inside.

**Comment by dmatte** [comment]
Hi,

this is actually fine.
The pieces are taken from the Mutopia project and the sheet music images
are then automatically aligned with the midi and audio.

For some of the pieces this automatic alignment procedure fails.
These are the pieces where no performance is available.
If you want to know more about this you can read about it in the [appendix](https://doi.org/10.5334/tismir.12.s1) of our TISMIR paper.

If you just want a list of the pieces where all the data is available
you can find it in the msmd/splits folder (e.g. all_split.yaml)
This is actually already a suggestion for a train / validation / test split.

If you want to know how to get started with the data and annotations you can also take a look at our [tutorials](https://github.com/CPJKU/msmd/tree/piece-performance-score/tutorials).

Best,
Matthias

**Comment by mjenrungrot** [comment]
Thanks @dmatte
