### ISSUE TITLE
Conversion between frequency and spectrogram frequency bins

### ISSUE THREAD

**Issue by Interspatial** [CPJKU/msmd#4]
Hi,
How do I convert between frequency of a pitch and the spectrogram frequency bin it belongs in?

**Comment by dmatte** [comment]
Hi,

we did not require this so far but you can check back on it in the file [midi_parser.py](https://github.com/CPJKU/msmd/blob/piece-performance-score/msmd/midi_parser.py)
where all the signal processing is going on.

In general we were using madmom to compute our logarithmic-filtered-spectrograms.
As far as I read from the documentation of (madmom.audio.spectrogram) you should have a property called "bin_frequencies" that should give you what you want.

You can read more about this in the documentation of [madmom](https://madmom.readthedocs.io/en/latest/modules/audio/spectrogram.html).

Hope this helps a little.

Best,
Matthias

**Comment by Interspatial** [comment]
I'm using `audio.filters.midi2hz(note_event[1])` to convert the pitch from the note event to frequency, then `bins = audio.LogarithmicFilteredSpectrogram(spec[0], num_bands=16, fmin=30, fmax=6000, fps=FPS, frame_size=FRAME_SIZE, sample_rate=SAMPLE_RATE).bin_frequencies` to get the bins. Does this look right? It's decently accurate but very off for certain pitches.

**Comment by dmatte** [comment]
Both processing steps look fine to me but I think I do not fully understand
what you would like to do.

`audio.filters.midi2hz(note_event[1])` will give you the fundamental frequency of a certain midi pitch

`bins = audio.LogarithmicFilteredSpectrogram(spec[0], num_bands=16, fmin=30, fmax=6000, fps=FPS, frame_size=FRAME_SIZE, sample_rate=SAMPLE_RATE).bin_frequencies` just gives you the center frequencies assigned to each spectrogram bin. This is after application of a semi-logarithmic filter-bank.

> It's decently accurate but very off for certain pitches.

It is not yet clear to me what you mean by accurate. Is this related to the MSMD dataset or a general signal processing question?
